# Structure of a Function

In [2]:
def welcome_message():
  print("hello user")

In [4]:
welcome_message()

hello user

In [5]:
def welcome_message(user="None"):
  print(f"hello {user}")

In [6]:
welcome_message("Phitron")

hello Phitron

In [7]:
def adder(a,b):
  """
  add two numbers
  a->int
  b->int

  """
  return a+b

In [8]:
print(adder(2,3))

5

In [9]:
help(adder)

Help on function adder in module __main__:

adder(a, b)
    add two numbers
    a->int
    b->int

In [10]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.

# Different types of Arguments

In [12]:
#positional arguments
def adder(a,b,c) :
  print(f"{a},{b},{c}")


adder(10,30,20)

10,30,20

In [15]:
def adder(*args): #args takes inp as tuple
  print(args)

  for i in args:
    print(i)

adder(10,30,60,70)

(10, 30, 60, 70)
10
30
60
70

In [16]:
#keyword arguments
def adder(a,b,c,d):
  print(f"a={a},b={b},c={c},d={d}")

adder(10,100,30,69)

a=10,b=100,c=30,d=69

In [19]:
def mul_keyargs(**kwargs): # takes inp as dict
  print(kwargs)

  for k,v in kwargs.items():
    print(f"{k}={v}")

mul_keyargs(a=20,b=40,x=50,y=69)

{'a': 20, 'b': 40, 'x': 50, 'y': 69}
a=20
b=40
x=50
y=69

# Return type of a func

In [20]:
#return nothing
def welcome_message():
  print("Hello!")
print(type(welcome_message()))

Hello!
<class 'NoneType'>

In [22]:
def adder(a,b) :
  sum = a+b
  return sum

print(type(adder(10,20)))

<class 'int'>

In [24]:
def adder(a,b) :
  sum = a+b
  return sum

print(type(adder(10.5,20)))

<class 'float'>

In [25]:
def welcome_message(user="None"):
  return f"hello {user}"

print(type(welcome_message()))

<class 'str'>

In [27]:
def adder(a,b) :
  sum = a+b
  return a,b

print(type(adder(10.5,20)))
x,y=adder(10,20)
print(x,y)

<class 'tuple'>
10 20

# Iterator

In [33]:
#iterating through a set
s = {10 , 20 , 30 , 40 , 50 }
it=iter(s)
print(next(it))
print(next(it))
print(next(it))
print(next(it))
print(next(it))

50
20
40
10
30

In [40]:
#iterating through a dict(keys)
d={"name":"Hamim","age":20,"weight":70}
# print(type(d))

it=iter(d)
print(next(it))
print(next(it))
print(next(it))

name
age
weight

In [42]:
#iterating through a dict(values)
d={"name":"Hamim","age":20,"weight":70}
# print(type(d))

it=iter(d.values())
print(next(it))
print(next(it))
print(next(it))

Hamim
20
70

In [45]:
#iterating through a dict(key,values)
d={"name":"Hamim","age":20,"weight":70}
# print(type(d))

it=iter(d.items())
print(next(it))
print(next(it))
print(next(it))

print(type(it))

('name', 'Hamim')
('age', 20)
('weight', 70)
<class 'dict_itemiterator'>

In [46]:
it = iter(d.items())

while True:
    try:
        key, value = next(it)
        print(key, value)
    except StopIteration:
        break

name Hamim
age 20
weight 70

# Generator

In [50]:
lst = [ x for x in range(500) ] # dataset

def data_loader(chunk_size,lst):
    for i in range(0,len(lst),chunk_size):
        yield lst[i:i+chunk_size]


x = data_loader(5,lst)

print(next(x))
print(next(x))
print(next(x))
print(x)
print(type(x))

[0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]
[10, 11, 12, 13, 14]
<generator object data_loader at 0x79b455d01a80>
<class 'generator'>

# Lemda,Map and Apply function

In [51]:
import pandas as pd


df = pd.DataFrame({'temperature (F)': [32, 212, 98.6, 68]})
df

df['temperature (C)'] = df['temperature (F)'].apply(lambda x: (x - 32) * 5/9)
df

   temperature (F)  temperature (C)
0             32.0              0.0
1            212.0            100.0
2             98.6             37.0
3             68.0             20.0

In [57]:
import pandas as pd


df = pd.DataFrame({'A': [1, 2, 3, 4], 'B': [5, 6, 7, 8]})

df

df['A'] = df['A'].map(lambda x: x ** 0.5)


df

          A  B
0  1.000000  5
1  1.414214  6
2  1.732051  7
3  2.000000  8

In [58]:
import pandas as pd

df = pd.DataFrame({'total_spent': [120, 600, 450, 800]})

# Creating a 'High Value' feature on the fly
df['is_high_value'] = df['total_spent'].apply(lambda x: 1 if x > 500 else 0)

df

   total_spent  is_high_value
0          120              0
1          600              1
2          450              0
3          800              1