In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [24]:
df=pd.read_csv('heart.csv')
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [25]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [26]:
df.duplicated().sum()

np.int64(723)

In [27]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,1025.000000,1025.000000,1025.000000,1025.000000,1025.00000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000
mean,54.434146,0.695610,0.942439,131.611707,246.00000,0.149268,0.529756,149.114146,0.336585,1.071512,1.385366,0.754146,2.323902,0.513171
std,9.072290,0.460373,1.029641,17.516718,51.59251,0.356527,0.527878,23.005724,0.472772,1.175053,0.617755,1.030798,0.620660,0.500070
min,29.000000,0.000000,0.000000,94.000000,126.00000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.000000,0.000000,0.000000,120.000000,211.00000,0.000000,0.000000,132.000000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,56.000000,1.000000,1.000000,130.000000,240.00000,0.000000,1.000000,152.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,275.00000,0.000000,1.000000,166.000000,1.000000,1.800000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.00000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [28]:
df[['cp','thal']].describe()

                cp         thal
count  1025.000000  1025.000000
mean      0.942439     2.323902
std       1.029641     0.620660
min       0.000000     0.000000
25%       0.000000     2.000000
50%       1.000000     2.000000
75%       2.000000     3.000000
max       3.000000     3.000000

In [29]:
print("Shape before encoding:", df.shape)

Shape before encoding: (1025, 14)

In [30]:
from sklearn.preprocessing import OneHotEncoder

ohe=OneHotEncoder(sparse_output=False).set_output(transform='pandas')

encoded_df=ohe.fit_transform(df[['cp','thal']])

encoded_df

      cp_0  cp_1  cp_2  cp_3  thal_0  thal_1  thal_2  thal_3
0      1.0   0.0   0.0   0.0     0.0     0.0     0.0     1.0
1      1.0   0.0   0.0   0.0     0.0     0.0     0.0     1.0
2      1.0   0.0   0.0   0.0     0.0     0.0     0.0     1.0
3      1.0   0.0   0.0   0.0     0.0     0.0     0.0     1.0
4      1.0   0.0   0.0   0.0     0.0     0.0     1.0     0.0
...    ...   ...   ...   ...     ...     ...     ...     ...
1020   0.0   1.0   0.0   0.0     0.0     0.0     1.0     0.0
1021   1.0   0.0   0.0   0.0     0.0     0.0     0.0     1.0
1022   1.0   0.0   0.0   0.0     0.0     0.0     1.0     0.0
1023   1.0   0.0   0.0   0.0     0.0     0.0     1.0     0.0
1024   1.0   0.0   0.0   0.0     0.0     0.0     0.0     1.0

[1025 rows x 8 columns]

In [31]:
df=pd.concat([df,encoded_df],axis=1)

df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,...,thal,target,cp_0,cp_1,cp_2,cp_3,thal_0,thal_1,thal_2,thal_3
0,52,1,0,125,212,0,1,168,0,1.0,...,3,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,53,1,0,140,203,1,0,155,1,3.1,...,3,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,70,1,0,145,174,0,1,125,1,2.6,...,3,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,61,1,0,148,203,0,1,161,0,0.0,...,3,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,62,0,0,138,294,1,1,106,0,1.9,...,2,0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,...,2,1,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1021,60,1,0,125,258,0,0,141,1,2.8,...,3,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1022,47,1,0,110,275,0,0,118,1,1.0,...,2,0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1023,50,0,0,110,254,0,0,159,0,0.0,...,2,1,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1024,54,1,0,120,188,0,1,113,0,1.4,...,3,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [32]:
df.drop(['cp','thal'],axis=1,inplace=True)

df

,age,sex,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,target,cp_0,cp_1,cp_2,cp_3,thal_0,thal_1,thal_2,thal_3
0,52,1,125,212,0,1,168,0,1.0,2,2,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,53,1,140,203,1,0,155,1,3.1,0,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,70,1,145,174,0,1,125,1,2.6,0,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,61,1,148,203,0,1,161,0,0.0,2,1,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,62,0,138,294,1,1,106,0,1.9,1,3,0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,140,221,0,1,164,1,0.0,2,0,1,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1021,60,1,125,258,0,0,141,1,2.8,1,1,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1022,47,1,110,275,0,0,118,1,1.0,1,1,0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1023,50,0,110,254,0,0,159,0,0.0,2,0,1,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1024,54,1,120,188,0,1,113,0,1.4,1,1,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [33]:
df.shape

(1025, 20)

## 03 label encoding

In [34]:
df = sns.load_dataset('tips')

df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [35]:
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder

le=LabelEncoder()

df['sex']=le.fit_transform(df['sex'])

df

     total_bill   tip  sex smoker   day    time  size
0         16.99  1.01    0     No   Sun  Dinner     2
1         10.34  1.66    1     No   Sun  Dinner     3
2         21.01  3.50    1     No   Sun  Dinner     3
3         23.68  3.31    1     No   Sun  Dinner     2
4         24.59  3.61    0     No   Sun  Dinner     4
..          ...   ...  ...    ...   ...     ...   ...
239       29.03  5.92    1     No   Sat  Dinner     3
240       27.18  2.00    0    Yes   Sat  Dinner     2
241       22.67  2.00    1    Yes   Sat  Dinner     2
242       17.82  1.75    1     No   Sat  Dinner     2
243       18.78  3.00    0     No  Thur  Dinner     2

[244 rows x 7 columns]

In [36]:
df['smoker']=le.fit_transform(df['smoker'])

df

     total_bill   tip  sex  smoker   day    time  size
0         16.99  1.01    0       0   Sun  Dinner     2
1         10.34  1.66    1       0   Sun  Dinner     3
2         21.01  3.50    1       0   Sun  Dinner     3
3         23.68  3.31    1       0   Sun  Dinner     2
4         24.59  3.61    0       0   Sun  Dinner     4
..          ...   ...  ...     ...   ...     ...   ...
239       29.03  5.92    1       0   Sat  Dinner     3
240       27.18  2.00    0       1   Sat  Dinner     2
241       22.67  2.00    1       1   Sat  Dinner     2
242       17.82  1.75    1       0   Sat  Dinner     2
243       18.78  3.00    0       0  Thur  Dinner     2

[244 rows x 7 columns]

In [37]:
def tip_cat(tip):
  if tip<3:
    return 'Low'
  elif tip<6:
    return 'Medium'
  else:
    return 'High'

df['Tip_Category']=df['tip'].apply(tip_cat)

In [38]:
df

     total_bill   tip  sex  smoker   day    time  size Tip_Category
0         16.99  1.01    0       0   Sun  Dinner     2          Low
1         10.34  1.66    1       0   Sun  Dinner     3          Low
2         21.01  3.50    1       0   Sun  Dinner     3       Medium
3         23.68  3.31    1       0   Sun  Dinner     2       Medium
4         24.59  3.61    0       0   Sun  Dinner     4       Medium
..          ...   ...  ...     ...   ...     ...   ...          ...
239       29.03  5.92    1       0   Sat  Dinner     3       Medium
240       27.18  2.00    0       1   Sat  Dinner     2          Low
241       22.67  2.00    1       1   Sat  Dinner     2          Low
242       17.82  1.75    1       0   Sat  Dinner     2          Low
243       18.78  3.00    0       0  Thur  Dinner     2       Medium

[244 rows x 8 columns]

In [46]:
tip_enc=OrdinalEncoder(categories=[['Low','Medium','High']])

df['Tip_Category_encoded']=tip_enc.fit_transform(df[['Tip_Category']])

df

,total_bill,tip,sex,smoker,day,time,size,Tip_Category,Tip_Category_encoded
0,16.99,1.01,0,0,Sun,Dinner,2,Low,0.0
1,10.34,1.66,1,0,Sun,Dinner,3,Low,0.0
2,21.01,3.50,1,0,Sun,Dinner,3,Medium,1.0
3,23.68,3.31,1,0,Sun,Dinner,2,Medium,1.0
4,24.59,3.61,0,0,Sun,Dinner,4,Medium,1.0
...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,1,0,Sat,Dinner,3,Medium,1.0
240,27.18,2.00,0,1,Sat,Dinner,2,Low,0.0
241,22.67,2.00,1,1,Sat,Dinner,2,Low,0.0
242,17.82,1.75,1,0,Sat,Dinner,2,Low,0.0
243,18.78,3.00,0,0,Thur,Dinner,2,Medium,1.0

In [48]:
df.sample(10)

,total_bill,tip,sex,smoker,day,time,size,Tip_Category,Tip_Category_encoded
220,12.16,2.20,1,1,Fri,Lunch,2,Low,0.0
36,16.31,2.00,1,0,Sat,Dinner,3,Low,0.0
107,25.21,4.29,1,1,Sat,Dinner,2,Medium,1.0
71,17.07,3.00,0,0,Sat,Dinner,3,Medium,1.0
141,34.30,6.70,1,0,Thur,Lunch,6,High,2.0
135,8.51,1.25,0,0,Thur,Lunch,2,Low,0.0
216,28.15,3.00,1,1,Sat,Dinner,5,Medium,1.0
94,22.75,3.25,0,0,Fri,Dinner,2,Medium,1.0
31,18.35,2.50,1,0,Sat,Dinner,4,Low,0.0
182,45.35,3.50,1,1,Sun,Dinner,3,Medium,1.0