# Registered email: ammarhamim7@gmail.com

# Starter Code

In [ ]:
import numpy as np
import pandas as pd

np.random.seed(24)

num_employees = 50  # you can increase this if needed

# Employee data
emp_ids = np.arange(101, 101 + num_employees)
emp_ages = np.random.randint(20, 55, num_employees)
emp_income = np.random.randint(35000, 95000, num_employees)

# Fixed set of roles (repetition allowed)
roles_list = [
    "HR Manager",
    "Software Developer",
    "Accountant",
    "Marketing Executive",
    "Sales Executive",
    "Backend Developer",
    "HR Executive",
    "Financial Analyst",
    "Digital Marketer",
    "Operations Manager"
]

emp_roles = np.random.choice(roles_list, num_employees)

# Create DataFrame
data = pd.DataFrame({
    "emp_id": emp_ids,
    "emp_age": emp_ages,
    "emp_salary": emp_income,
    "role": emp_roles
})

# Save dataset
data.to_csv("staff_data.csv", index=False)

# Question_1

In [ ]:
print(emp_ages)
print(emp_income)

print("\nFor age arr:")
print(emp_ages.dtype)
print(emp_ages.ndim)
print(emp_ages.shape)
print(emp_ages.size)

print("\nFor Salary array:")
print(emp_income.dtype)
print(emp_income.ndim)
print(emp_income.shape)
print(emp_income.size)

[54 23 20 43 37 37 21 35 24 38 31 35 29 38 27 45 51 48 20 32 51 53 21 26
 53 37 26 21 45 30 20 47 53 53 23 24 21 30 27 25 39 20 47 41 22 52 42 54
 31 50]
[51725 38495 35452 82295 72187 58915 76159 92864 76155 90494 68641 48079
 56879 83682 94722 91041 48899 68744 63187 74146 75641 47678 76760 78354
 60584 79898 59682 71888 51086 73700 82550 71447 76100 72269 73314 87428
 94427 84188 52013 63326 44396 59500 55523 58602 90794 41061 82331 73048
 59727 50398]

For age arr:
int64
1
(50,)
50

For Salary array:
int64
1
(50,)
50

# Question_2

In [ ]:
max_sal=np.max(emp_income)
min_sal=np.min(emp_income)
avg_sal=np.mean(emp_income)
avg_age=np.mean(emp_ages)

print(f"Maximum salary: {max_sal}")
print(f"MInimum salary: {min_sal}")
print(f"Average salary: {avg_sal}")
print(f"Average age: {avg_age}")

Maximum salary: 94722
MInimum salary: 35452
Average salary: 68409.48
Average age: 35.44

# Question_3

In [ ]:
filtered_emp=data[(emp_ages>=25) & (emp_ages<=40) & (emp_income>50000)]

print(filtered_emp)
print(f"Total: {len(filtered_emp)}")

    emp_id  emp_age  emp_salary                role
4      105       37       72187   Backend Developer
5      106       37       58915          HR Manager
7      108       35       92864     Sales Executive
9      110       38       90494        HR Executive
10     111       31       68641   Backend Developer
12     113       29       56879     Sales Executive
13     114       38       83682  Operations Manager
14     115       27       94722    Digital Marketer
19     120       32       74146   Backend Developer
23     124       26       78354  Software Developer
25     126       37       79898  Operations Manager
26     127       26       59682    Digital Marketer
29     130       30       73700          Accountant
37     138       30       84188          Accountant
38     139       27       52013          HR Manager
39     140       25       63326     Sales Executive
48     149       31       59727    Digital Marketer
Total: 17

# Question_4

In [ ]:
avg_age=np.mean(emp_ages)
updated_ages=emp_ages.copy()

updated_ages[emp_ages<avg_age]+=4
updated_ages[emp_ages>=avg_age]+=2

print("Original Array: \n",emp_ages)
print("Updated Array: \n",updated_ages)
print("Avg age: ",avg_age)

Original Array:
 [54 23 20 43 37 37 21 35 24 38 31 35 29 38 27 45 51 48 20 32 51 53 21 26
 53 37 26 21 45 30 20 47 53 53 23 24 21 30 27 25 39 20 47 41 22 52 42 54
 31 50]
Updated Array:
 [56 27 24 45 39 39 25 39 28 40 35 39 33 40 31 47 53 50 24 36 53 55 25 30
 55 39 30 25 47 34 24 49 55 55 27 28 25 34 31 29 41 24 49 43 26 54 44 56
 35 52]
Avg age:  35.44

# Question_5

In [ ]:
tech_roles = ["Software Developer", "Backend Developer"]
# print(emp_roles)

is_tech=np.isin(emp_roles,tech_roles)

updated_sal=emp_income.copy()
updated_sal[is_tech]=updated_sal[is_tech]*1.08

updated_total=np.sum(updated_sal)
total=np.sum(emp_income)

diff=updated_total-total

print(f"Old total = {total}")
print(f"Updated total = {updated_total}")
print(f"Differene = {diff}")

Old total = 3420474
Updated total = 3490239
Differene = 69765

# Question_6

In [ ]:
df=pd.read_csv("staff_data.csv")

df.head(3)

   emp_id  emp_age  emp_salary                role
0     101       54       51725          HR Manager
1     102       23       38495          Accountant
2     103       20       35452  Operations Manager

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   emp_id      50 non-null     int64
 1   emp_age     50 non-null     int64
 2   emp_salary  50 non-null     int64
 3   role        50 non-null     object
dtypes: int64(3), object(1)
memory usage: 1.7+ KB

In [ ]:
df.describe()

          emp_id    emp_age    emp_salary
count   50.00000  50.000000     50.000000
mean   125.50000  35.440000  68409.480000
std     14.57738  11.768446  15727.122334
min    101.00000  20.000000  35452.000000
25%    113.25000  24.250000  57309.750000
50%    125.50000  35.000000  72037.500000
75%    137.75000  46.500000  79512.000000
max    150.00000  54.000000  94722.000000

# Question_7

In [ ]:
filtered_df=df[["emp_id","emp_age","role"]]

filtered_df

    emp_id  emp_age                 role
0      101       54           HR Manager
1      102       23           Accountant
2      103       20   Operations Manager
3      104       43     Digital Marketer
4      105       37    Backend Developer
5      106       37           HR Manager
6      107       21    Backend Developer
7      108       35      Sales Executive
8      109       24      Sales Executive
9      110       38         HR Executive
10     111       31    Backend Developer
11     112       35  Marketing Executive
12     113       29      Sales Executive
13     114       38   Operations Manager
14     115       27     Digital Marketer
15     116       45    Financial Analyst
16     117       51      Sales Executive
17     118       48   Operations Manager
18     119       20   Software Developer
19     120       32    Backend Developer
20     121       51      Sales Executive
21     122       53      Sales Executive
22     123       21           Accountant
23     124       26   Software Developer
24     125       53         HR Executive
25     126       37   Operations Manager
26     127       26     Digital Marketer
27     128       21         HR Executive
28     129       45   Software Developer
29     130       30           Accountant
30     131       20      Sales Executive
31     132       47  Marketing Executive
32     133       53     Digital Marketer
33     134       53    Backend Developer
34     135       23   Software Developer
35     136       24   Software Developer
36     137       21      Sales Executive
37     138       30           Accountant
38     139       27           HR Manager
39     140       25      Sales Executive
40     141       39  Marketing Executive
41     142       20     Digital Marketer
42     143       47         HR Executive
43     144       41           Accountant
44     145       22         HR Executive
45     146       52           HR Manager
46     147       42   Software Developer
47     148       54   Software Developer
48     149       31     Digital Marketer
49     150       50  Marketing Executive

In [ ]:
filtered_df=filtered_df[
    (filtered_df["emp_age"]>=25) & (filtered_df["emp_age"]<=40)
    ]

filtered_df

    emp_id  emp_age                 role
4      105       37    Backend Developer
5      106       37           HR Manager
7      108       35      Sales Executive
9      110       38         HR Executive
10     111       31    Backend Developer
11     112       35  Marketing Executive
12     113       29      Sales Executive
13     114       38   Operations Manager
14     115       27     Digital Marketer
19     120       32    Backend Developer
23     124       26   Software Developer
25     126       37   Operations Manager
26     127       26     Digital Marketer
29     130       30           Accountant
37     138       30           Accountant
38     139       27           HR Manager
39     140       25      Sales Executive
40     141       39  Marketing Executive
48     149       31     Digital Marketer

In [ ]:
filtered_df.sort_values("emp_id")

filtered_df

    emp_id  emp_age                 role
4      105       37    Backend Developer
5      106       37           HR Manager
7      108       35      Sales Executive
9      110       38         HR Executive
10     111       31    Backend Developer
11     112       35  Marketing Executive
12     113       29      Sales Executive
13     114       38   Operations Manager
14     115       27     Digital Marketer
19     120       32    Backend Developer
23     124       26   Software Developer
25     126       37   Operations Manager
26     127       26     Digital Marketer
29     130       30           Accountant
37     138       30           Accountant
38     139       27           HR Manager
39     140       25      Sales Executive
40     141       39  Marketing Executive
48     149       31     Digital Marketer

In [ ]:
filtered_df.tail(3)

    emp_id  emp_age                 role
39     140       25      Sales Executive
40     141       39  Marketing Executive
48     149       31     Digital Marketer

# Question_8

In [ ]:
filter_hr=df[df["role"].str.contains("HR")]

print(filter_hr)

print(f"total hr emp: {len(filter_hr)}")

    emp_id  emp_age  emp_salary          role
0      101       54       51725    HR Manager
5      106       37       58915    HR Manager
9      110       38       90494  HR Executive
24     125       53       60584  HR Executive
27     128       21       71888  HR Executive
38     139       27       52013    HR Manager
42     143       47       55523  HR Executive
44     145       22       90794  HR Executive
45     146       52       41061    HR Manager
total hr emp: 9

# Question_9

In [ ]:
sort_df=df.sort_values(["emp_age","emp_salary"],ascending=[True,False])
res=sort_df[["emp_id","role","emp_salary"]]
res.head()

    emp_id                role  emp_salary
30     131     Sales Executive       82550
18     119  Software Developer       63187
41     142    Digital Marketer       59500
2      103  Operations Manager       35452
36     137     Sales Executive       94427

# Question_10

In [ ]:
df2 = df.copy()
df2["emp_salary"] = df2["emp_salary"].astype(float)

df2["previous_salary"]=df2["emp_salary"]
tech_roles=["Software Developer","Backend Developer"]

df2.loc[df2["role"].isin(tech_roles),"emp_salary"]*=1.12
df2.loc[~df2["role"].isin(tech_roles),"emp_salary"]*=1.05

df2["new_salary"]=df2["emp_salary"]

df2["increase_of_salary"]=df2["new_salary"]-df2["previous_salary"]

print(df2[["role","previous_salary","new_salary","increase_of_salary"]])

                   role  previous_salary  new_salary  increase_of_salary
0            HR Manager          51725.0    54311.25             2586.25
1            Accountant          38495.0    40419.75             1924.75
2    Operations Manager          35452.0    37224.60             1772.60
3      Digital Marketer          82295.0    86409.75             4114.75
4     Backend Developer          72187.0    80849.44             8662.44
5            HR Manager          58915.0    61860.75             2945.75
6     Backend Developer          76159.0    85298.08             9139.08
7       Sales Executive          92864.0    97507.20             4643.20
8       Sales Executive          76155.0    79962.75             3807.75
9          HR Executive          90494.0    95018.70             4524.70
10    Backend Developer          68641.0    76877.92             8236.92
11  Marketing Executive          48079.0    50482.95             2403.95
12      Sales Executive          56879.0    59722.95             2843.95
13   Operations Manager          83682.0    87866.10             4184.10
14     Digital Marketer          94722.0    99458.10             4736.10
15    Financial Analyst          91041.0    95593.05             4552.05
16      Sales Executive          48899.0    51343.95             2444.95
17   Operations Manager          68744.0    72181.20             3437.20
18   Software Developer          63187.0    70769.44             7582.44
19    Backend Developer          74146.0    83043.52             8897.52
20      Sales Executive          75641.0    79423.05             3782.05
21      Sales Executive          47678.0    50061.90             2383.90
22           Accountant          76760.0    80598.00             3838.00
23   Software Developer          78354.0    87756.48             9402.48
24         HR Executive          60584.0    63613.20             3029.20
25   Operations Manager          79898.0    83892.90             3994.90
26     Digital Marketer          59682.0    62666.10             2984.10
27         HR Executive          71888.0    75482.40             3594.40
28   Software Developer          51086.0    57216.32             6130.32
29           Accountant          73700.0    77385.00             3685.00
30      Sales Executive          82550.0    86677.50             4127.50
31  Marketing Executive          71447.0    75019.35             3572.35
32     Digital Marketer          76100.0    79905.00             3805.00
33    Backend Developer          72269.0    80941.28             8672.28
34   Software Developer          73314.0    82111.68             8797.68
35   Software Developer          87428.0    97919.36            10491.36
36      Sales Executive          94427.0    99148.35             4721.35
37           Accountant          84188.0    88397.40             4209.40
38           HR Manager          52013.0    54613.65             2600.65
39      Sales Executive          63326.0    66492.30             3166.30
40  Marketing Executive          44396.0    46615.80             2219.80
41     Digital Marketer          59500.0    62475.00             2975.00
42         HR Executive          55523.0    58299.15             2776.15
43           Accountant          58602.0    61532.10             2930.10
44         HR Executive          90794.0    95333.70             4539.70
45           HR Manager          41061.0    43114.05             2053.05
46   Software Developer          82331.0    92210.72             9879.72
47   Software Developer          73048.0    81813.76             8765.76
48     Digital Marketer          59727.0    62713.35             2986.35
49  Marketing Executive          50398.0    52917.90             2519.90